import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import AppContextProvider from "./context/AppContext";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <ToastContainer position="buttom-right"/>
        <AppContextProvider>
        {children}
        </AppContextProvider>
        
      </body>
    </html>
  );
}
